### ISSUE TITLE
Allow Account Public Key Search Functionality

### ISSUE THREAD

**Issue by sekoyalabs** [nemgrouplimited/symbol-explorer#853] opened 2021-03-25 17:38 UTC
explorer.symbolblockchain.io does not allow an individual to search by public key. Suggestion to add the ability for users to identify accounts based on public key.

**Comment by AnthonyLaw** [comment] 2021-03-26 05:22
You can try on the URL.

```
http://explorer.symbolblockchain.io/accounts/<publicKey>
```

example:
http://explorer.symbolblockchain.io/accounts/4F866C157C0F9D3741295EC1C6CABDDF14AE2B02B6E97BF7B5CE616FF191F4FE

**Comment by sekoyalabs** [comment] 2021-03-28 11:43
Thank you @AnthonyLaw. It would be a good enhancement to allow this through the search bar in the upper right hand of the page as well

**Comment by AnthonyLaw** [comment] 2021-03-29 09:54
Sure, we have created the issue for this #854

**Comment by OlegMakarenko** [comment] 2021-03-29 20:37
Duplicate of #854

**Closed by OlegMakarenko** 2021-03-29 20:37 UTC
