### ISSUE TITLE
Accounts with a public key are not displayed correctly

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-explorer#676] opened 2020-10-08 17:58 UTC
Several attempts are always required to display an account with a public key. 

![Screenshot_20201008_192007](https://user-images.githubusercontent.com/46584115/95495696-0c41fa80-09a0-11eb-9d79-d486d33b306d.png)

**Comment by cryptoBeliever** [comment] 2020-10-08 20:49
It looks like duplicate of https://github.com/nemgrouplimited/symbol-explorer/issues/663.
@AnthonyLaw 663 is already closed. When it will be deployed?

**Comment by AnthonyLaw** [comment] 2020-10-09 06:20
@cryptoBeliever Hi there, we are going to release another version late today or tomorrow.
Hopefully, tomorrow or next tomorrow will be deployed :)

**Comment by AnthonyLaw** [comment] 2020-10-26 13:53
fixes in #663..

**Closed by AnthonyLaw** 2020-10-26 13:53 UTC
