### ISSUE TITLE
Api node is not shown in explorer when there is only one API node.

### ISSUE THREAD

**Issue by Wayonb** [nemgrouplimited/symbol-explorer#687] opened 2020-10-14 00:58 UTC
Currently it seem like the explorer only use the node/peers to get the list of nodes to display.  This should be combine with node/info which will return the information for the api-node.

![ApiNode_not_shown](https://user-images.githubusercontent.com/44558938/95931122-4fcca800-0d96-11eb-8216-d6ccd5ab7c24.png)

**Comment by AnthonyLaw** [comment] 2020-10-14 06:36
Thanks, for the feedback
duplicate of #658

**Closed by AnthonyLaw** 2020-10-14 06:36 UTC
